config/routes.rb
DiamondApp::Application.routes.draw do
  resources :templates

  resources :my_diamonds

end

app/models/my_diamond.rb
class MyDiamond < ActiveRecord::Base
  belongs_to :template
end

app/models/template.rb
class Template < ActiveRecord::Base
  has_many :my_diamonds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_diamonds_controller.rb
class MyDiamondsController < ApplicationController
  before_action :set_my_diamond, only: [:show, :edit, :update, :destroy]

  # GET /my_diamonds
  # GET /my_diamonds.json
  def index
    @my_diamonds = MyDiamond.all
  end

  # GET /my_diamonds/1
  # GET /my_diamonds/1.json
  def show
  end

  # GET /my_diamonds/new
  def new
    @my_diamond = MyDiamond.new
    @templates = Template.all
    gon.template = @templates
  end

  # GET /my_diamonds/1/edit
  def edit
  end

  # POST /my_diamonds
  # POST /my_diamonds.json
  def create
    @my_diamond = MyDiamond.new(my_diamond_params)

    respond_to do |format|
      if @my_diamond.save
        format.html { redirect_to @my_diamond, notice: 'My diamond was successfully created.' }
        format.json { render action: 'show', status: :created, location: @my_diamond }
      else
        format.html { render action: 'new' }
        format.json { render json: @my_diamond.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_diamonds/1
  # PATCH/PUT /my_diamonds/1.json
  def update
    respond_to do |format|
      if @my_diamond.update(my_diamond_params)
        format.html { redirect_to @my_diamond, notice: 'My diamond was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @my_diamond.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_diamonds/1
  # DELETE /my_diamonds/1.json
  def destroy
    @my_diamond.destroy
    respond_to do |format|
      format.html { redirect_to my_diamonds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_diamond
      @my_diamond = MyDiamond.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_diamond_params
      params.require(:my_diamond).permit(:price, :carat, :shape, :template_id)
    end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render action: 'show', status: :created, location: @template }
      else
        format.html { render action: 'new' }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def template_params
      params.require(:template).permit(:name, :description, :min_color, :min_cut, :min_clarity, :min_polish, :min_symmetry, :min_flour)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_diamonds_helper.rb
module MyDiamondsHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DiamondApp</title>
  <%= include_gon %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag params[:controller], media: 'all', "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag params[:controller], media: 'all', "data-turbolinks-track" => true %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_diamonds/_form.html.erb
<%= form_for(@my_diamond) do |f| %>
  <% if @my_diamond.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_diamond.errors.count, "error") %> prohibited this my_diamond from being saved:</h2>

      <ul>
      <% @my_diamond.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :carat %><br>
    <%= f.text_field :carat %>
  </div>
  <div class="field">
    <%= f.label :shape %><br>
    <%= f.text_field :shape %>
  </div>
  <div class="field">
    <%= f.label :template_id %><br>
    <%= f.number_field :template_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<div>
  <ul>
      <% @templates.each do |template| %>
        <li><a class="templateInput" href="#" data-id = "<%=template.id%>"><%= template.name %>, <%= template.description %></a></li>
      <% end %>
  </ul>
</div>

app/views/my_diamonds/edit.html.erb
<h1>Editing my_diamond</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_diamond %> |
<%= link_to 'Back', my_diamonds_path %>

app/views/my_diamonds/index.html.erb
<h1>Listing my_diamonds</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Carat</th>
      <th>Shape</th>
      <th>Template</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @my_diamonds.each do |my_diamond| %>
      <tr>
        <td><%= my_diamond.price %></td>
        <td><%= my_diamond.carat %></td>
        <td><%= my_diamond.shape %></td>
        <td><%= my_diamond.template_id %></td>
        <td><%= link_to 'Show', my_diamond %></td>
        <td><%= link_to 'Edit', edit_my_diamond_path(my_diamond) %></td>
        <td><%= link_to 'Destroy', my_diamond, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My diamond', new_my_diamond_path %>

app/views/my_diamonds/new.html.erb
<h1>New my_diamond</h1>

<%= render 'form' %>

<%= link_to 'Back', my_diamonds_path %>

app/views/my_diamonds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @my_diamond.price %>
</p>

<p>
  <strong>Carat:</strong>
  <%= @my_diamond.carat %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @my_diamond.shape %>
</p>

<p>
  <strong>Template:</strong>
  <%= @my_diamond.template_id %>
</p>

<%= link_to 'Edit', edit_my_diamond_path(@my_diamond) %> |
<%= link_to 'Back', my_diamonds_path %>

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :min_color %><br>
    <%= f.text_field :min_color %>
  </div>
  <div class="field">
    <%= f.label :min_cut %><br>
    <%= f.text_field :min_cut %>
  </div>
  <div class="field">
    <%= f.label :min_clarity %><br>
    <%= f.text_field :min_clarity %>
  </div>
  <div class="field">
    <%= f.label :min_polish %><br>
    <%= f.text_field :min_polish %>
  </div>
  <div class="field">
    <%= f.label :min_symmetry %><br>
    <%= f.text_field :min_symmetry %>
  </div>
  <div class="field">
    <%= f.label :min_flour %><br>
    <%= f.text_field :min_flour %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Min color</th>
      <th>Min cut</th>
      <th>Min clarity</th>
      <th>Min polish</th>
      <th>Min symmetry</th>
      <th>Min flour</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.description %></td>
        <td><%= template.min_color %></td>
        <td><%= template.min_cut %></td>
        <td><%= template.min_clarity %></td>
        <td><%= template.min_polish %></td>
        <td><%= template.min_symmetry %></td>
        <td><%= template.min_flour %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @template.description %>
</p>

<p>
  <strong>Min color:</strong>
  <%= @template.min_color %>
</p>

<p>
  <strong>Min cut:</strong>
  <%= @template.min_cut %>
</p>

<p>
  <strong>Min clarity:</strong>
  <%= @template.min_clarity %>
</p>

<p>
  <strong>Min polish:</strong>
  <%= @template.min_polish %>
</p>

<p>
  <strong>Min symmetry:</strong>
  <%= @template.min_symmetry %>
</p>

<p>
  <strong>Min flour:</strong>
  <%= @template.min_flour %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>